import type { Metadata } from "next";
import { Inter, Karla } from "next/font/google";
import "./globals.css";
import BaseAppWrapper from "./BaseWrapper";
const karla = Karla({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BaseAppWrapper fontFamily={karla.className}>{children}</BaseAppWrapper>
  );
}
