import type { Metadata } from "next";
import { Inter, Karla, Space_Mono, Trispace, Poppins } from "next/font/google";
import "./globals.css";
import BaseAppWrapper from "./BaseWrapper";
import ReduxWrapper from "./ReduxWrapper";
const karla = Karla({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});
const space_mono = Space_Mono({ weight: ["400", "700"], subsets: ["latin"] });
const trispace = Trispace({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Octo - The smart learning AI tutor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxWrapper>
      <BaseAppWrapper fontFamily={poppins.className}>{children}</BaseAppWrapper>
    </ReduxWrapper>
  );
}
