export const SUBJECTS = [
  "Algebra",
  "Linear Algebra",
  "Quadratic Equations",
  "Systems of Equations",
  "Arithmetic",
  "Addition",
  "Subtraction",
  "Multiplication",
  "Division",
  "Decimals",
  "Fractions",
  "Calculus",
  "Differentiation",
  "Integration",
  "Limits",
  "Geometry",
  "Euclidean Geometry",
  "Coordinate Geometry",
  "Solid Geometry",
  "Statistics",
  "Descriptive Statistics",
  "Inferential Statistics",
  "Probability Distributions",
  "Number Theory",
  "Prime Numbers",
  "Divisibility",
  "Factorization",
  "Modular Arithmetic",
  "Logic",
  "Propositional Logic",
  "Predicate Logic",
  "Boolean Algebra",
  "Trigonometry",
  "Trigonometric Functions",
  "Identities",
  "Solving Triangles",
  "Data Analysis",
  "Data Representation",
  "Data Interpretation",
  "Data Visualization",
  "Functions",
  "Linear Functions",
  "Quadratic Functions",
  "Exponential Functions",
  "Probability",
  "Combinatorics",
  "Conditional Probability",
  "Expected Value",
  "Algorithms",
  "Sorting Algorithms",
  "Search Algorithms",
  "Graph Algorithms",
];
