export const SUBJECTS_LIST = [
  "Mathematics",
  "Physics",
  "Biology",
  "Chemistry",
  "Language Arts",
  "Social Studies",
  "Foreign Languages",
  "Physical Education / Health Education",
  "Computer Science / Information Technology",
  "Environmental Education",
  "Technology Education",
];

export const MATHS_SUBJECTS_LIST = [
  "Algebra",
  "Linear Algebra",
  "Quadratic Equations",
  "Systems of Equations",
  "Arithmetic",
  "Addition",
  "Subtraction",
  "Multiplication",
  "Division",
  "Decimals",
  "Fractions",
  "Calculus",
  "Differentiation",
  "Integration",
  "Limits",
  "Geometry",
  "Euclidean Geometry",
  "Coordinate Geometry",
  "Solid Geometry",
  "Statistics",
  "Descriptive Statistics",
  "Inferential Statistics",
  "Probability Distributions",
  "Number Theory",
  "Prime Numbers",
  "Divisibility",
  "Factorization",
  "Modular Arithmetic",
  "Logic",
  "Propositional Logic",
  "Predicate Logic",
  "Boolean Algebra",
  "Trigonometry",
  "Trigonometric Functions",
  "Identities",
  "Solving Triangles",
  "Data Analysis",
  "Data Representation",
  "Data Interpretation",
  "Data Visualization",
  "Functions",
  "Linear Functions",
  "Quadratic Functions",
  "Exponential Functions",
  "Probability",
  "Combinatorics",
  "Conditional Probability",
  "Expected Value",
  "Algorithms",
  "Sorting Algorithms",
  "Search Algorithms",
  "Graph Algorithms",
];
export const PHYSICS_SUBJECT_LIST = [
  "Mechanics",
  "Kinematics",
  "Dynamics",
  "Newton's Laws of Motion",
  "Forces and Motion",
  "Circular Motion and Gravitation",
  "Energy and Work",
  "Conservation Laws",
  "Thermodynamics",
  "Temperature and Heat",
  "Laws of Thermodynamics",
  "Heat Transfer (Conduction, Convection, Radiation)",
  "Thermodynamic Processes",
  "Thermal Expansion",
  "Waves and Optics",
  "Properties of Waves",
  "Wave Interference",
  "Sound Waves and Acoustics",
  "Light Waves and Optics",
  "Reflection and Refraction",
  "Lenses and Mirrors",
  "Color Theory",
  "Electricity and Magnetism",
  "Electric Charge and Electric Fields",
  "Electric Potential and Voltage",
  "Electric Current and Circuits",
  "Ohm's Law",
  "Magnetism and Magnetic Fields",
  "Electromagnetism",
  "Electromagnetic Induction",
  "Atomic and Nuclear Physics",
  "Structure of the Atom",
  "Atomic Models",
  "Radioactivity and Nuclear Reactions",
  "Nuclear Energy",
  "Particle Physics",
  "Fluid Mechanics",
  "Properties of Fluids",
  "Pressure and Buoyancy",
  "Fluid Dynamics",
  "Bernoulli's Principle",
  "Relativity and Astrophysics",
  "Special Theory of Relativity",
  "General Theory of Relativity",
  "Cosmology",
  "Stellar Physics",
  "Planetary Physics",
  "Modern Physics",
  "Quantum Mechanics",
  "Wave-Particle Duality",
  "Photoelectric Effect",
  "Atomic Spectra",
  "Particle Physics",
  "Nuclear Physics",
];

export const BIOLOGY_SUBJECT_LIST = [
  "Cell Biology",
  "Cell Structure and Function",
  "Cell Organelles",
  "Cell Membrane Transport",
  "Cell Division (Mitosis and Meiosis)",
  "Cell Cycle Regulation",
  "Genetics",
  "Mendelian Genetics",
  "Punnett Squares",
  "Chromosomes and Inheritance",
  "DNA Structure and Replication",
  "Gene Expression and Regulation",
  "Genetic Engineering and Biotechnology",
  "Evolution",
  "Theory of Evolution",
  "Natural Selection",
  "Evidence for Evolution",
  "Mechanisms of Evolution (Mutation, Genetic Drift, Gene Flow)",
  "Ecology",
  "Ecosystems and Biomes",
  "Population Dynamics",
  "Community Interactions (Competition, Predation, Symbiosis)",
  "Energy Flow in Ecosystems (Food Chains and Food Webs)",
  "Biogeochemical Cycles (Carbon Cycle, Nitrogen Cycle, Water Cycle)",
  "Physiology",
  "Human Anatomy and Physiology",
  "Plant Anatomy and Physiology",
  "Circulatory System",
  "Respiratory System",
  "Digestive System",
  "Nervous System",
  "Endocrine System",
  "Immune System",
  "Microbiology",
  "Bacteria",
  "Viruses",
  "Protists",
  "Fungi",
  "Microbial Diseases",
  "Microbial Ecology",
  "Botany",
  "Plant Structure and Function",
  "Photosynthesis",
  "Plant Reproduction",
  "Plant Growth and Development",
  "Plant Hormones",
  "Plant Adaptations",
  "Zoology",
  "Animal Classification",
  "Animal Behavior",
  "Reproduction in Animals",
  "Animal Development",
  "Animal Adaptations",
  "Comparative Anatomy",
  "Biochemistry",
  "Biomolecules (Carbohydrates, Lipids, Proteins, Nucleic Acids)",
  "Enzymes and Enzyme Kinetics",
  "Metabolism (Anabolism and Catabolism)",
  "Cellular Respiration",
  "Photosynthesis",
  "Biomes and Biodiversity",
  "Terrestrial Biomes",
  "Aquatic Biomes",
  "Biodiversity Hotspots",
  "Conservation Biology",
  "Threats to Biodiversity",
];

export const CHEMISTRY_SUBJECT_LIST = [
  "Atomic Structure",
  "Atomic Theory",
  "Subatomic Particles (Protons, Neutrons, Electrons)",
  "Atomic Models (Bohr Model, Quantum Mechanical Model)",
  "Atomic Number and Mass Number",
  "Isotopes and Atomic Mass",
  "Periodic Table and Periodicity",
  "Periodic Law",
  "Periodic Trends (Atomic Radius, Ionization Energy, Electronegativity)",
  "Groups and Periods",
  "Classification of Elements",
  "Chemical Bonding",
  "Ionic Bonding",
  "Covalent Bonding",
  "Metallic Bonding",
  "Lewis Structures",
  "VSEPR Theory (Valence Shell Electron Pair Repulsion)",
  "Molecular Geometry",
  "Chemical Reactions",
  "Types of Chemical Reactions (Synthesis, Decomposition, Single Replacement, Double Replacement, Combustion)",
  "Balancing Chemical Equations",
  "Stoichiometry",
  "Reaction Rates",
  "Chemical Kinetics",
  "States of Matter",
  "Solid, Liquid, and Gas",
  "Phase Changes (Melting, Freezing, Vaporization, Condensation, Sublimation, Deposition)",
  "Gas Laws (Boyle's Law, Charles's Law, Avogadro's Law, Ideal Gas Law)",
  "Thermochemistry",
  "Heat and Temperature",
  "Specific Heat Capacity",
  "Enthalpy (Heat of Reaction, Heat of Formation, Heat of Combustion)",
  "Endothermic and Exothermic Reactions",
  "Hess's Law",
  "Solutions and Solubility",
  "Solubility Rules",
  "Factors Affecting Solubility",
  "Concentration Units (Molarity, Molality, Mole Fraction)",
  "Colligative Properties (Boiling Point Elevation, Freezing Point Depression, Osmotic Pressure)",
  "Acids and Bases",
  "Arrhenius Theory",
  "Brønsted-Lowry Theory",
  "pH Scale",
  "Acid-Base Titration",
  "Buffer Solutions",
  "Hydrolysis",
  "Electrochemistry",
  "Oxidation-Reduction Reactions",
  "Electrochemical Cells",
  "Galvanic Cells",
  "Electrolysis",
  "Faraday's Laws of Electrolysis",
  "Organic Chemistry",
  "Hydrocarbons (Alkanes, Alkenes, Alkynes)",
  "Functional Groups (Alcohols, Aldehydes, Ketones, Carboxylic Acids, Amines, Esters)",
  "Isomerism",
  "Organic Reactions (Substitution, Addition, Elimination, Condensation, Hydrolysis)",
  "Nuclear Chemistry",
  "Nuclear Reactions (Alpha Decay, Beta Decay, Gamma Decay)",
  "Half-Life",
  "Nuclear Fission",
  "Nuclear Fusion",
  "Radioactive Decay",
  "Analytical Chemistry",
  "Qualitative Analysis",
  "Quantitative Analysis",
  "Spectroscopy",
  "Chromatography",
  "Mass Spectrometry",
];

export const LANGUAGE_ARTS_SUBJECTS_LIST = [
  "Reading Comprehension",
  "Literal Comprehension",
  "Inferential Comprehension",
  "Critical Comprehension",
  "Analyzing Text Structure",
  "Identifying Main Ideas and Supporting Details",
  "Making Inferences and Drawing Conclusions",
  "Literature",
  "Fiction (Novels, Short Stories, Drama)",
  "Non-fiction (Essays, Biographies, Autobiographies, Speeches)",
  "Poetry (Forms, Themes, Literary Devices)",
  "Literary Analysis (Characterization, Plot, Setting, Theme)",
  "Literary Elements and Techniques",
  "Writing Process",
  "Pre-writing (Brainstorming, Outlining)",
  "Drafting",
  "Revising",
  "Editing",
  "Publishing",
  "Peer Review and Feedback",
  "Grammar and Mechanics",
  "Parts of Speech (Nouns, Verbs, Adjectives, Adverbs, Pronouns, Conjunctions, Prepositions, Interjections)",
  "Sentence Structure (Simple, Compound, Complex, Compound-Complex)",
  "Punctuation (Period, Comma, Semicolon, Colon, Apostrophe, Quotation Marks, Dash)",
  "Capitalization",
  "Spelling Rules",
  "Vocabulary",
  "Word Meaning and Context Clues",
  "Synonyms and Antonyms",
  "Word Roots, Prefixes, and Suffixes",
  "Academic and Domain-Specific Vocabulary",
  "Vocabulary Acquisition Strategies",
  "Literary Elements",
  "Plot (Exposition, Rising Action, Climax, Falling Action, Resolution)",
  "Characterization (Protagonist, Antagonist, Round, Flat, Dynamic, Static)",
  "Setting (Time, Place, Atmosphere)",
  "Theme",
  "Symbolism",
  "Irony (Verbal, Situational, Dramatic)",
  "Writing Genres",
  "Narrative Writing (Personal Narratives, Short Stories)",
  "Expository Writing (Essays, Reports)",
  "Persuasive Writing (Argumentative Essays, Op-Eds)",
  "Descriptive Writing",
  "Creative Writing (Poetry, Fiction)",
  "Technical Writing",
  "Speaking and Listening",
  "Active Listening",
  "Effective Speaking Techniques",
  "Public Speaking Skills",
  "Oral Presentations",
  "Group Discussions and Debates",
  "Research Skills",
  "Formulating Research Questions",
  "Gathering and Evaluating Sources",
  "Note-taking",
  "Paraphrasing and Summarizing",
  "Citing Sources (MLA, APA)",
  "Literary Movements and Periods",
  "Renaissance Literature",
  "Romanticism",
  "Realism and Naturalism",
  "Modernism",
  "Postmodernism",
  "Contemporary Literature",
];

export const SOCIAL_STUDIES_SUBJECTS_LIST = [
  "History",
  "Ancient Civilizations (Mesopotamia, Egypt, Greece, Rome, China, India, etc.)",
  "Medieval Europe",
  "Renaissance and Reformation",
  "Age of Exploration",
  "Enlightenment",
  "Industrial Revolution",
  "World Wars (World War I, World War II)",
  "Cold War Era",
  "Contemporary History",
  "Geography",
  "Physical Geography (Landforms, Climate, Biomes)",
  "Human Geography (Population, Settlements, Migration)",
  "Cultural Geography (Languages, Religions, Ethnicities)",
  "Political Geography (Borders, States, Nations)",
  "Economic Geography (Resources, Trade, Development)",
  "Civics and Government",
  "Democratic Principles",
  "Constitution and Bill of Rights",
  "Branches of Government (Legislative, Executive, Judicial)",
  "Federalism",
  "Rights and Responsibilities of Citizens",
  "Elections and Voting",
  "Political Parties and Ideologies",
  "Civil Rights and Liberties",
  "Economics",
  "Basic Economic Concepts (Supply and Demand, Scarcity, Opportunity Cost)",
  "Economic Systems (Capitalism, Socialism, Communism)",
  "Market Structures (Monopoly, Oligopoly, Perfect Competition)",
  "Macroeconomics (GDP, Unemployment, Inflation)",
  "Microeconomics (Individual and Firm Behavior)",
  "International Trade and Globalization",
  "Personal Finance and Budgeting",
  "Sociology",
  "Social Institutions (Family, Education, Religion, Government, Economy)",
  "Social Stratification and Inequality",
  "Socialization",
  "Cultural Diversity",
  "Deviance and Social Control",
  "Social Change",
  "Anthropology",
  "Cultural Anthropology",
  "Archaeology",
  "Physical Anthropology",
  "Linguistic Anthropology",
  "Ethnography",
  "Current Events and Global Issues",
  "International Relations",
  "Human Rights",
  "Environmental Issues",
  "Globalization",
  "Terrorism and Conflict",
  "Health and Pandemics",
  "Social Justice Movements",
  "Historical Analysis and Critical Thinking",
  "Primary and Secondary Sources",
  "Historical Interpretation",
  "Cause and Effect",
  "Chronological Reasoning",
  "Analyzing Historical Perspectives",
  "Historical Empathy",
];

export const FOREIGN_LANGUAGS_SUBJECT_LIST = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin Chinese",
  "Japanese",
  "Italian",
  "Latin",
  "Russian",
  "Arabic",
  "Portuguese",
];

export const PHYSICAL_EDU_SUBJECT_LIST = [
  "Physical Fitness",
  "Components of Fitness",
  "Fitness Testing and Assessment",
  "Fitness Goals and Personal Fitness Plans",
  "Exercise Prescription",
  "Sports and Activities",
  "Team Sports",
  "Individual Sports",
  "Outdoor Activities",
  "Recreational Games and Activities",
  "Movement Skills and Techniques",
  "Fundamental Movement Skills",
  "Sport-Specific Skills and Techniques",
  "Proper Form and Mechanics",
  "Skill Development and Progression",
  "Health and Wellness",
  "Nutrition and Healthy Eating Habits",
  "Body Systems",
  "Personal Hygiene and Self-Care",
  "Sleep and Rest",
  "Stress Management and Relaxation Techniques",
  "Safety and Injury Prevention",
  "First Aid and CPR Training",
  "Sports Safety Guidelines",
  "Injury Prevention Strategies",
  "Proper Equipment Use and Maintenance",
  "Mental and Emotional Health",
  "Mental Health Awareness",
  "Coping Skills",
  "Goal Setting and Decision Making",
  "Self-Esteem and Confidence Building",
  "Resilience and Positive Thinking",
  "Substance Abuse Prevention",
  "Drug and Alcohol Education",
  "Effects of Substance Abuse on Physical and Mental Health",
  "Peer Pressure and Refusal Skills",
  "Healthy Alternatives and Positive Peer Relationships",
  "Human Growth and Development",
  "Puberty Education",
  "Reproductive Health and Sexuality Education",
  "Anatomy and Physiology",
  "Pregnancy Prevention",
  "Gender and Sexual Identity",
  "Personal and Social Responsibility",
  "Teamwork and Cooperation",
  "Sportsmanship and Fair Play",
  "Leadership Skills",
  "Conflict Resolution",
  "Respect for Diversity and Inclusion",
  "Lifelong Fitness and Physical Activity",
  "Benefits of Regular Exercise",
  "Setting Fitness Goals",
  "Developing Healthy Habits for Life",
  "Community Fitness Resources",
  "Physical Activity and Aging",
];

export const COMPUTER_SCIENCE_SUBJECT_LIST = [
  "Understanding Computers:",
  "Parts of a Computer",
  "How Computers Work",
  "Using Operating Systems like Windows or macOS",
  "Coding and Programming:",
  "Introduction to Coding",
  "Learning Languages like Python or Scratch",
  "Creating Simple Programs and Games",
  "Building Websites:",
  "Basics of HTML and CSS",
  "Making Web Pages with Text and Images",
  "Introduction to Website Design",
  "Internet Safety:",
  "Online Safety Tips",
  "Protecting Personal Information",
  "Recognizing Online Threats",
  "Cybersecurity:",
  "Understanding Cybersecurity Risks",
  "Keeping Passwords Safe",
  "Recognizing Phishing Attempts",
  "Connecting Computers:",
  "Introduction to Networking",
  "Basics of Wi-Fi and Ethernet",
  "Sharing Files and Printers",
  "Introduction to Databases:",
  "What is a Database?",
  "Basics of Organizing Information",
  "Using Simple Database Software",
  "Introduction to Software Development:",
  "Understanding How Software is Made",
  "Creating Simple Programs and Apps",
  "Testing and Fixing Problems",
  "Data and Information:",
  "Basics of Collecting and Organizing Data",
  "Simple Data Analysis",
  "Understanding Charts and Graphs",
  "Exploring New Technologies:",
  "Introduction to New Technologies like AI and VR",
  "Learning About Future Career Opportunities",
  "Understanding How Technology Impacts Society",
];

export const ENVIRONMENTAL_EDU_SUBJECT_LIST = [
  "Understanding the Environment:",
  "Introduction to Ecology",
  "Ecosystems and Biodiversity",
  "Interactions between Living Organisms and their Environment",
  "Environmental Issues:",
  "Climate Change and Global Warming",
  "Pollution (Air, Water, Soil)",
  "Deforestation and Habitat Loss",
  "Waste Management and Recycling",
  "Conservation and Preservation:",
  "Endangered Species and Wildlife Conservation",
  "Protected Areas and National Parks",
  "Sustainable Resource Management",
  "Renewable and Non-Renewable Resources:",
  "Introduction to Energy Sources",
  "Renewable Energy (Solar, Wind, Hydroelectric, Geothermal)",
  "Fossil Fuels and their Environmental Impact",
  "Sustainable Consumption Practices",
  "Water Conservation and Management:",
  "Importance of Clean Water",
  "Water Cycle and Water Pollution",
  "Water Conservation Strategies",
  "Air Quality and Pollution:",
  "Understanding Air Pollution",
  "Sources of Air Pollution (Industry, Transportation, Agriculture)",
  "Effects of Air Pollution on Health and Environment",
  "Solutions for Improving Air Quality",
  "Environmental Sustainability:",
  "Sustainable Living Practices",
  "Reduce, Reuse, Recycle",
  "Carbon Footprint Reduction",
  "Eco-Friendly Transportation",
  "Environmental Policy and Advocacy:",
  "Role of Government in Environmental Protection",
  "Environmental Laws and Regulations",
  "Advocacy and Community Action for Environmental Causes",
  "Environmental Education and Awareness:",
  "Promoting Environmental Awareness",
  "Environmental Education Programs and Initiatives",
  "Engaging in Environmental Projects and Activities",
  "Global Perspectives on Environmental Issues:",
  "Understanding Environmental Challenges in Different Regions",
  "International Cooperation for Environmental Conservation",
  "Environmental Justice and Equity",
];

export const TECHNOLOGY_SUBJECT_LIST = [
  "Introduction to Technology:",
  "Understanding Technology and its Role in Society",
  "Evolution of Technology Over Time",
  "Basic Concepts such as Hardware, Software, and User Interfaces",
  "Digital Literacy:",
  "Basic Computer Skills (Typing, File Management, Using Applications)",
  "Internet Navigation and Online Research",
  "Email Etiquette and Digital Communication",
  "Information and Communication Technology (ICT):",
  "Introduction to ICT Tools and Software (Word Processing, Spreadsheets, Presentation Software)",
  "Digital Citizenship and Responsible Internet Use",
  "Using Technology for Collaboration and Communication",
  "Problem Solving and Critical Thinking:",
  "Introduction to Design Thinking Process",
  "Identifying Problems and Needs",
  "Brainstorming Solutions and Prototyping",
  "Engineering Design:",
  "Introduction to Engineering Design Process",
  "Creating and Testing Solutions to Design Challenges",
  "Understanding Engineering Principles such as Structural Stability and Mechanical Advantage",
  "Robotics and Automation:",
  "Introduction to Robotics and Automation Concepts",
  "Building and Programming Simple Robots",
  "Understanding Sensors and Actuators",
  "Digital Design and Multimedia:",
  "Introduction to Graphic Design Principles",
  "Creating Digital Artwork and Designs",
  "Introduction to Multimedia Production (Audio, Video, Animation)",
  "Technological Systems:",
  "Understanding Technological Systems (e.g., Transportation Systems, Communication Systems, Energy Systems)",
  "Components and Interactions within Technological Systems",
  "Technological Innovation and Entrepreneurship:",
  "Introduction to Innovation and Creativity",
  "Identifying Opportunities for Technological Innovation",
  "Basics of Entrepreneurship and Business Planning",
  "Emerging Technologies:",
  "Introduction to Emerging Technologies (e.g., Artificial Intelligence, Virtual Reality, Internet of Things)",
  "Exploring Future Trends in Technology",
  "Ethical Considerations and Implications of New Technologies",
];
